//! Duxo Firebase/RTDB signaling module.
//!
//! §0.6 — RTDB structure: sessions/, codes/, rateLimit/.
//! RTDB is for LIVE signaling only (offer/answer, ICE candidates, status).
//! Durable records go in Firestore (§6.3) — never per-frame data here.
//!
//! The host agent uses the Firebase REST API directly (no Rust SDK needed)
//! with a fresh ID token for each request. This keeps the dependency tree thin.

use crate::types::{Result, SessionStatus, DuxoError};
use rand::Rng;

/// §0.6 — 8-digit codes (100M combinations). Generated by the host, looked up
/// by the viewer. 24-hour expiry via client-side timestamp check (Path A).
pub fn generate_code() -> String {
    let mut rng = rand::thread_rng();
    let code: u32 = rng.gen_range(1_0000_0000..10_0000_0000);
    code.to_string()
}

/// §1.1 — Create the RTDB session skeleton when the host launches.
/// Writes to sessions/{sessionId} and codes/{code} atomically via a
/// multi-path PATCH against the RTDB REST API.
pub async fn create_session(
    database_url: &str,
    id_token: &str,
    _project_id: &str,
    host_uid: &str,
    host_platform: &str,
) -> Result<(String, String)> {
    let session_id = generate_session_id();
    let code = generate_code();

    let client = reqwest::Client::new();
    // RTDB REST API uses: .json suffix and auth query param
    // Docs: https://firebase.google.com/docs/reference/rest/database
    let url = format!(
        "{}/.json?auth={}",
        database_url.trim_end_matches('/'), id_token
    );

    // Multi-path update: sessions/{id} and codes/{code} in one atomic PATCH
    let mut body = serde_json::json!({});
    body[format!("sessions/{}", session_id)] = serde_json::json!({
        "hostId": host_uid,
        "hostPlatform": host_platform,
        "viewerId": null,
        "status": "waiting",
        "offer": null,
        "answer": null,
        "hostCandidates": {},
        "viewerCandidates": {},
        "createdAt": { ".sv": "timestamp" },
        "updatedAt": { ".sv": "timestamp" }
    });
    body[format!("codes/{}", code)] = serde_json::json!(session_id);

    client.patch(&url).json(&body).send().await?
        .error_for_status()
        .map_err(|e| DuxoError::Firebase(e.to_string()))?;

    tracing::info!(
        session_id = %session_id,
        code = %code,
        platform = host_platform,
        "session created"
    );

    Ok((session_id, code))
}

/// §1.6-B — Update a field in the live RTDB session.
pub async fn update_session_field(
    database_url: &str,
    id_token: &str,
    _project_id: &str,
    session_id: &str,
    field: &str,
    value: serde_json::Value,
) -> Result<()> {
    let client = reqwest::Client::new();
    // RTDB REST API: PATCH with field selector
    let url = format!(
        "{}/sessions/{}.json?auth={}",
        database_url.trim_end_matches('/'), session_id, id_token
    );

    let mut patch = serde_json::json!({});
    patch[field] = value;
    client.patch(&url).json(&patch)
        .send().await?
        .error_for_status()
        .map_err(|e| DuxoError::Firebase(e.to_string()))?;

    Ok(())
}

/// §1.1 — End the session (status → "ended"). Either peer can do this.
pub async fn end_session(
    database_url: &str,
    id_token: &str,
    project_id: &str,
    session_id: &str,
) -> Result<()> {
    update_session_field(
        database_url, id_token, project_id, session_id,
        "status",
        serde_json::json!("ended"),
    ).await
}

/// §1.1 — Host writes ALLOWED or DENIED. This is the most important write
/// in the entire app (§2.4).
pub async fn set_permission(
    database_url: &str,
    id_token: &str,
    project_id: &str,
    session_id: &str,
    allowed: bool,
) -> Result<()> {
    let status = if allowed {
        SessionStatus::Allowed
    } else {
        SessionStatus::Denied
    };
    update_session_field(
        database_url, id_token, project_id, session_id,
        "status",
        serde_json::json!(status.to_string()),
    ).await
}

/// Generate a unique session ID (16-char hex).
fn generate_session_id() -> String {
    use rand::distributions::Alphanumeric;
    rand::thread_rng()
        .sample_iter(&Alphanumeric)
        .take(16)
        .map(char::from)
        .collect()
}
