//! Duxo Firebase/RTDB signaling module.
//!
//! §0.6 — RTDB structure: sessions/, codes/, rateLimit/.
//! RTDB is for LIVE signaling only (offer/answer, ICE candidates, status).
//! Durable records go in Firestore (§6.3) — never per-frame data here.
//!
//! The host agent uses the Firebase REST API directly (no Rust SDK needed)
//! with a fresh ID token for each request. This keeps the dependency tree thin.

use crate::types::{DuxoError, Result, SessionStatus};
use rand::Rng;

/// §0.6 — 8-digit codes (100M combinations). Generated by the host, looked up
/// by the viewer. 24-hour expiry via client-side timestamp check (Path A).
///
/// The range is `0..100_000_000` zero-padded, not `10_000_000..100_000_000`.
/// Padding is what makes the space the full 100M §0.7 counts on for its
/// brute-force maths; dropping the leading zero would cost 10% of it and make
/// the length vary, and every consumer of this code has a fixed idea of the
/// length: the RTDB rule for `codes/$code` requires `$code.length == 8`, the
/// viewer's input is capped at 8 digits, `/api/resolve-code` refuses anything
/// but `^[0-9]{8}$`, and `format_code` groups as `XXXX XXXX`.
pub fn generate_code() -> String {
    let mut rng = rand::thread_rng();
    let code: u32 = rng.gen_range(0..100_000_000);
    format!("{code:08}")
}

/// Turn an RTDB HTTP failure into something that names the likely cause.
///
/// A 404 from the database root is the single most misleading response here:
/// it does not mean "that path is empty", it means the *database instance*
/// does not exist. A project can have Firebase enabled, a valid service
/// account, and correct credentials, and still 404 every call because nobody
/// ever created the Realtime Database — §0.13 item 4. Reported as a bare
/// "Firebase error: 404 Not Found", that sends you looking at rules, tokens
/// and paths, none of which are the problem.
fn rtdb_error(context: &str, status: reqwest::StatusCode, database_url: &str) -> DuxoError {
    if status == reqwest::StatusCode::NOT_FOUND {
        return DuxoError::Firebase(format!(
            "{context}: {database_url} returned 404. The Realtime Database for \
             this project probably does not exist — create it in the Firebase \
             console (Build → Realtime Database → Create Database). A 404 here \
             is the whole instance missing, not an empty path."
        ));
    }
    if status == reqwest::StatusCode::UNAUTHORIZED || status == reqwest::StatusCode::FORBIDDEN {
        return DuxoError::Firebase(format!(
            "{context}: {database_url} returned {status}. Either this device's \
             token has expired, or the security rules in firebase/ have not \
             been deployed — an undeployed ruleset refuses writes the app \
             depends on."
        ));
    }
    DuxoError::Firebase(format!("{context}: {status}"))
}

/// §1.1 — Create the RTDB session skeleton when the host launches.
/// Writes to sessions/{sessionId} and codes/{code} atomically via a
/// multi-path PATCH against the RTDB REST API.
pub async fn create_session(
    database_url: &str,
    id_token: &str,
    _project_id: &str,
    host_uid: &str,
    host_platform: &str,
) -> Result<(String, String)> {
    let session_id = generate_session_id();
    let code = generate_code();

    let client = reqwest::Client::new();
    // RTDB REST API uses: .json suffix and auth query param
    // Docs: https://firebase.google.com/docs/reference/rest/database
    let url = format!(
        "{}/.json?auth={}",
        database_url.trim_end_matches('/'),
        id_token
    );

    // Multi-path update: sessions/{id} and codes/{code} in one atomic PATCH
    let mut body = serde_json::json!({});
    body[format!("sessions/{}", session_id)] = serde_json::json!({
        "hostId": host_uid,
        "hostPlatform": host_platform,
        "viewerId": null,
        "status": "waiting",
        "offer": null,
        "answer": null,
        "hostCandidates": {},
        "viewerCandidates": {},
        "createdAt": { ".sv": "timestamp" },
        "updatedAt": { ".sv": "timestamp" }
    });
    // §0.7 — the code node records who owns it, not just where it points.
    // A bare string gave the RTDB rules nothing to check a writer against, so
    // "only the host that created this code may replace or retire it" could
    // not be expressed and any signed-in account could repoint or delete it.
    body[format!("codes/{}", code)] = serde_json::json!({
        "sessionId": session_id,
        "hostId": host_uid,
    });

    let resp = client.patch(&url).json(&body).send().await?;
    if !resp.status().is_success() {
        return Err(rtdb_error(
            "could not create the session node",
            resp.status(),
            database_url,
        ));
    }

    tracing::info!(
        session_id = %session_id,
        code = %code,
        platform = host_platform,
        "session created"
    );

    Ok((session_id, code))
}

/// §1.6-B — Update a field in the live RTDB session.
pub async fn update_session_field(
    database_url: &str,
    id_token: &str,
    _project_id: &str,
    session_id: &str,
    field: &str,
    value: serde_json::Value,
) -> Result<()> {
    let client = reqwest::Client::new();
    // RTDB REST API: PATCH with field selector
    let url = format!(
        "{}/sessions/{}.json?auth={}",
        database_url.trim_end_matches('/'),
        session_id,
        id_token
    );

    let mut patch = serde_json::json!({});
    patch[field] = value;
    client
        .patch(&url)
        .json(&patch)
        .send()
        .await?
        .error_for_status()
        .map_err(|e| DuxoError::Firebase(crate::types::redact_secrets(&e.to_string())))?;

    Ok(())
}

/// §1.1 — End the session (status → "ended"). Either peer can do this.
pub async fn end_session(
    database_url: &str,
    id_token: &str,
    project_id: &str,
    session_id: &str,
) -> Result<()> {
    update_session_field(
        database_url,
        id_token,
        project_id,
        session_id,
        "status",
        serde_json::json!("ended"),
    )
    .await
}

/// §1.1 — Host writes ALLOWED or DENIED. This is the most important write
/// in the entire app (§2.4).
pub async fn set_permission(
    database_url: &str,
    id_token: &str,
    project_id: &str,
    session_id: &str,
    allowed: bool,
) -> Result<()> {
    let status = if allowed {
        SessionStatus::Allowed
    } else {
        SessionStatus::Denied
    };
    update_session_field(
        database_url,
        id_token,
        project_id,
        session_id,
        "status",
        serde_json::json!(status.to_string()),
    )
    .await
}

/// Generate a unique session ID (16-char hex).
fn generate_session_id() -> String {
    use rand::distributions::Alphanumeric;
    rand::thread_rng()
        .sample_iter(&Alphanumeric)
        .take(16)
        .map(char::from)
        .collect()
}

/// §1.6-B — read the whole live session node.
///
/// Returns `Ok(None)` when RTDB answers `null`, which is how a deleted or
/// never-created session reads. That is a normal end-of-session condition,
/// not a transport error, so it must not be conflated with one.
pub async fn read_session(
    database_url: &str,
    id_token: &str,
    session_id: &str,
) -> Result<Option<serde_json::Value>> {
    let client = reqwest::Client::new();
    let url = format!(
        "{}/sessions/{}.json?auth={}",
        database_url.trim_end_matches('/'),
        session_id,
        id_token
    );

    let resp = client.get(&url).send().await?;
    if !resp.status().is_success() {
        return Err(DuxoError::Firebase(format!(
            "session read failed: {}",
            resp.status()
        )));
    }

    let value: serde_json::Value = resp.json().await?;
    if value.is_null() {
        return Ok(None);
    }
    Ok(Some(value))
}

/// §0.6 — publish one ICE candidate at an indexed slot.
///
/// The RTDB `.validate` rule only admits indices 0–99, so the caller keeps its
/// own cursor; writing past 99 is refused at the rule layer rather than here.
pub async fn write_candidate(
    database_url: &str,
    id_token: &str,
    _project_id: &str,
    session_id: &str,
    bucket: &str,
    index: u32,
    candidate_json: &str,
) -> Result<()> {
    let client = reqwest::Client::new();
    let url = format!(
        "{}/sessions/{}/{}/{}.json?auth={}",
        database_url.trim_end_matches('/'),
        session_id,
        bucket,
        index,
        id_token
    );

    client
        .put(&url)
        .json(&serde_json::json!(candidate_json))
        .send()
        .await?
        .error_for_status()
        .map_err(|e| DuxoError::Firebase(crate::types::redact_secrets(&e.to_string())))?;

    Ok(())
}

/// §1.1 — retire a code at session end.
///
/// Without this, a code stays redeemable for its full 24-hour life pointing at
/// a session that has already ended, so a viewer who mistypes and lands on a
/// stale code gets a silent hang instead of "that code isn't valid".
pub async fn delete_code(database_url: &str, id_token: &str, code: &str) -> Result<()> {
    // The stored code has no space; the display form ("XXXX XXXX") does.
    let normalized: String = code.chars().filter(|c| c.is_ascii_digit()).collect();
    if normalized.is_empty() {
        return Ok(());
    }

    let client = reqwest::Client::new();
    let url = format!(
        "{}/codes/{}.json?auth={}",
        database_url.trim_end_matches('/'),
        normalized,
        id_token
    );

    client
        .delete(&url)
        .send()
        .await?
        .error_for_status()
        .map_err(|e| DuxoError::Firebase(crate::types::redact_secrets(&e.to_string())))?;

    Ok(())
}

/// §6.3 — write the durable session record to Firestore at session end.
///
/// The viewer's history page reads `sessionHistory`, and until now nothing
/// wrote it — every completed session vanished and the page was permanently
/// empty. Metadata only: timestamps, duration, platform. Never screen content.
pub struct SessionHistoryRecord<'a> {
    pub host_uid: &'a str,
    pub viewer_uid: &'a str,
    pub host_platform: &'a str,
    pub started_at_ms: i64,
    pub ended_at_ms: i64,
    pub end_reason: &'a str,
}

pub async fn write_session_history(
    project_id: &str,
    id_token: &str,
    record: &SessionHistoryRecord<'_>,
) -> Result<()> {
    let SessionHistoryRecord {
        host_uid,
        viewer_uid,
        host_platform,
        started_at_ms,
        ended_at_ms,
        end_reason,
    } = *record;

    let client = reqwest::Client::new();
    let url = format!(
        "https://firestore.googleapis.com/v1/projects/{project_id}/databases/(default)/documents/sessionHistory"
    );

    let duration_seconds = ((ended_at_ms - started_at_ms) / 1000).max(0);

    // Firestore's REST API wants explicitly typed field values.
    let body = serde_json::json!({
        "fields": {
            "hostUid":       { "stringValue":  host_uid },
            "viewerUid":     { "stringValue":  viewer_uid },
            "hostPlatform":  { "stringValue":  host_platform },
            "startedAt":     { "integerValue": started_at_ms.to_string() },
            "endedAt":       { "integerValue": ended_at_ms.to_string() },
            "durationSeconds": { "integerValue": duration_seconds.to_string() },
            "endReason":     { "stringValue":  end_reason },
        }
    });

    let resp = client
        .post(&url)
        .bearer_auth(id_token)
        .json(&body)
        .send()
        .await?;

    if !resp.status().is_success() {
        let status = resp.status();
        let text = resp.text().await.unwrap_or_default();
        return Err(DuxoError::Firebase(format!(
            "session history write failed ({status}): {text}"
        )));
    }

    tracing::info!(duration_seconds, end_reason, "session history recorded");
    Ok(())
}
#[cfg(test)]
mod rtdb_error_tests {
    use super::*;

    #[test]
    fn a_404_names_the_missing_database_rather_than_the_path() {
        // This is the failure a fresh project hits on its very first session,
        // and "404 Not Found" on its own sends you auditing rules and tokens.
        let e = rtdb_error(
            "x",
            reqwest::StatusCode::NOT_FOUND,
            "https://db.example.com",
        );
        let msg = e.to_string();
        assert!(msg.contains("does not exist"), "{msg}");
        assert!(msg.contains("Firebase console"), "{msg}");
    }

    #[test]
    fn a_401_points_at_tokens_and_undeployed_rules() {
        for status in [
            reqwest::StatusCode::UNAUTHORIZED,
            reqwest::StatusCode::FORBIDDEN,
        ] {
            let msg = rtdb_error("x", status, "https://db.example.com").to_string();
            assert!(msg.contains("deployed"), "{msg}");
        }
    }

    #[test]
    fn other_statuses_stay_terse() {
        // Guessing a cause for a 500 would be worse than reporting the code.
        let msg = rtdb_error("x", reqwest::StatusCode::INTERNAL_SERVER_ERROR, "u").to_string();
        assert!(!msg.contains("Firebase console"), "{msg}");
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The bug this pins: the range was `1_0000_0000..10_0000_0000`, which is
    /// 100,000,000 to 999,999,999 — nine digits, not eight. Nothing in the
    /// host itself objected, so the first symptom was that "Start a session"
    /// failed outright: the code node is written in the same atomic multi-path
    /// PATCH as the session node, and `codes/$code`'s rule requires
    /// `$code.length == 8`, so the whole write was refused and no session
    /// could ever be created. Had the rules been open, the code still could
    /// not have been entered — the viewer's input stops at 8 digits.
    #[test]
    fn codes_are_always_exactly_eight_digits() {
        for _ in 0..2_000 {
            let code = generate_code();
            assert_eq!(code.len(), 8, "code {code} is not 8 characters");
            assert!(
                code.chars().all(|c| c.is_ascii_digit()),
                "code {code} is not all digits"
            );
        }
    }

    /// §0.7's "100M combinations" only holds if the low end of the range is
    /// reachable, which means zero-padded codes have to be produced and kept
    /// as strings.
    #[test]
    fn low_codes_keep_their_leading_zeros() {
        assert_eq!(format!("{:08}", 42), "00000042");
        assert_eq!(format!("{:08}", 99_999_999u32), "99999999");
    }

    #[test]
    fn session_ids_are_url_safe_and_long_enough_to_be_unguessable() {
        let id = generate_session_id();
        assert_eq!(id.len(), 16);
        assert!(id.chars().all(|c| c.is_ascii_alphanumeric()));
    }
}
